server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/user_db1?createDatabaseIfNotExist=true
    username: root
    password: Riju@03Rai@07

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
